package hmapasinversa;
// Generated 28-feb-2017 16:09:16 by Hibernate Tools 4.3.1



/**
 * Autores generated by hbm2java
 */
public class Autores  implements java.io.Serializable {


     private String dni;
     private Personas personas;

    public Autores() {
    }

    public Autores(Personas personas) {
       this.personas = personas;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }




}


