package hmapasinversa;
// Generated 28-feb-2017 16:09:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conferencias generated by hbm2java
 */
public class Conferencias  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Date fechaHoraInicio;
     private double precio;
     private Set sesioneses = new HashSet(0);
     private Set participantesConferenciases = new HashSet(0);

    public Conferencias() {
    }

	
    public Conferencias(int id, String nombre, Date fechaHoraInicio, double precio) {
        this.id = id;
        this.nombre = nombre;
        this.fechaHoraInicio = fechaHoraInicio;
        this.precio = precio;
    }
    public Conferencias(int id, String nombre, Date fechaHoraInicio, double precio, Set sesioneses, Set participantesConferenciases) {
       this.id = id;
       this.nombre = nombre;
       this.fechaHoraInicio = fechaHoraInicio;
       this.precio = precio;
       this.sesioneses = sesioneses;
       this.participantesConferenciases = participantesConferenciases;
    }

    @Override
    public String toString() {
        return "Conferencias{" + "id=" + id + ", nombre=" + nombre + '}';
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaHoraInicio() {
        return this.fechaHoraInicio;
    }
    
    public void setFechaHoraInicio(Date fechaHoraInicio) {
        this.fechaHoraInicio = fechaHoraInicio;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set getSesioneses() {
        return this.sesioneses;
    }
    
    public void setSesioneses(Set sesioneses) {
        this.sesioneses = sesioneses;
    }
    public Set getParticipantesConferenciases() {
        return this.participantesConferenciases;
    }
    
    public void setParticipantesConferenciases(Set participantesConferenciases) {
        this.participantesConferenciases = participantesConferenciases;
    }




}


