package hmapasinversa;
// Generated 28-feb-2017 16:09:16 by Hibernate Tools 4.3.1



/**
 * ParticipantesConferencias generated by hbm2java
 */
public class ParticipantesConferencias  implements java.io.Serializable {


     private ParticipantesConferenciasId id;
     private Conferencias conferencias;
     private Participantes participantes;
     private boolean confirmado;

    public ParticipantesConferencias() {
    }

    public ParticipantesConferencias(ParticipantesConferenciasId id, Conferencias conferencias, Participantes participantes, boolean confirmado) {
       this.id = id;
       this.conferencias = conferencias;
       this.participantes = participantes;
       this.confirmado = confirmado;
    }
   
    public ParticipantesConferenciasId getId() {
        return this.id;
    }
    
    public void setId(ParticipantesConferenciasId id) {
        this.id = id;
    }
    public Conferencias getConferencias() {
        return this.conferencias;
    }
    
    public void setConferencias(Conferencias conferencias) {
        this.conferencias = conferencias;
    }
    public Participantes getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Participantes participantes) {
        this.participantes = participantes;
    }
    public boolean isConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }




}


