package hmapasinversa;
// Generated 28-feb-2017 16:09:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private Set articuloses = new HashSet(0);
     private Autores autores;
     private Participantes participantes;

    public Personas() {
    }

	
    public Personas(String dni, String nombre) {
        this.dni = dni;
        this.nombre = nombre;
    }
    public Personas(String dni, String nombre, Set articuloses, Autores autores, Participantes participantes) {
       this.dni = dni;
       this.nombre = nombre;
       this.articuloses = articuloses;
       this.autores = autores;
       this.participantes = participantes;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getArticuloses() {
        return this.articuloses;
    }
    
    public void setArticuloses(Set articuloses) {
        this.articuloses = articuloses;
    }
    public Autores getAutores() {
        return this.autores;
    }
    
    public void setAutores(Autores autores) {
        this.autores = autores;
    }
    public Participantes getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Participantes participantes) {
        this.participantes = participantes;
    }




}


