package hmapasinversa;
// Generated 28-feb-2017 16:09:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sesiones generated by hbm2java
 */
public class Sesiones  implements java.io.Serializable {


     private int id;
     private Articulos articulos;
     private Conferencias conferencias;
     private String nombre;
     private String info;
     private double fechaHoraInicio;
     private Set participanteses = new HashSet(0);

    public Sesiones() {
    }

	
    public Sesiones(int id, Articulos articulos, Conferencias conferencias, String nombre, String info, double fechaHoraInicio) {
        this.id = id;
        this.articulos = articulos;
        this.conferencias = conferencias;
        this.nombre = nombre;
        this.info = info;
        this.fechaHoraInicio = fechaHoraInicio;
    }
    public Sesiones(int id, Articulos articulos, Conferencias conferencias, String nombre, String info, double fechaHoraInicio, Set participanteses) {
       this.id = id;
       this.articulos = articulos;
       this.conferencias = conferencias;
       this.nombre = nombre;
       this.info = info;
       this.fechaHoraInicio = fechaHoraInicio;
       this.participanteses = participanteses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Conferencias getConferencias() {
        return this.conferencias;
    }
    
    public void setConferencias(Conferencias conferencias) {
        this.conferencias = conferencias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public double getFechaHoraInicio() {
        return this.fechaHoraInicio;
    }
    
    public void setFechaHoraInicio(double fechaHoraInicio) {
        this.fechaHoraInicio = fechaHoraInicio;
    }
    public Set getParticipanteses() {
        return this.participanteses;
    }
    
    public void setParticipanteses(Set participanteses) {
        this.participanteses = participanteses;
    }




}


