package hmapasinversa;
// Generated 01-mar-2017 18:25:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sesiones generated by hbm2java
 */
public class Sesiones  implements java.io.Serializable {


     private int id;
     private Articulos articulos;
     private Conferencias conferencias;
     private String nombre;
     private String tema;
     private Date fechaHoraInicio;
     private int duracion;
     private Set participanteses = new HashSet(0);

    public Sesiones() {
    }

	
    public Sesiones(int id, Articulos articulos, Conferencias conferencias, String nombre, String tema, Date fechaHoraInicio, int duracion) {
        this.id = id;
        this.articulos = articulos;
        this.conferencias = conferencias;
        this.nombre = nombre;
        this.tema = tema;
        this.fechaHoraInicio = fechaHoraInicio;
        this.duracion = duracion;
    }
    public Sesiones(int id, Articulos articulos, Conferencias conferencias, String nombre, String tema, Date fechaHoraInicio, int duracion, Set participanteses) {
       this.id = id;
       this.articulos = articulos;
       this.conferencias = conferencias;
       this.nombre = nombre;
       this.tema = tema;
       this.fechaHoraInicio = fechaHoraInicio;
       this.duracion = duracion;
       this.participanteses = participanteses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Conferencias getConferencias() {
        return this.conferencias;
    }
    
    public void setConferencias(Conferencias conferencias) {
        this.conferencias = conferencias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Date getFechaHoraInicio() {
        return this.fechaHoraInicio;
    }
    
    public void setFechaHoraInicio(Date fechaHoraInicio) {
        this.fechaHoraInicio = fechaHoraInicio;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }
    public Set getParticipanteses() {
        return this.participanteses;
    }
    
    public void setParticipanteses(Set participanteses) {
        this.participanteses = participanteses;
    }




}


