/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxectoaad;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;

/**
 *
 * @author AnxoPregal
 */
public class ArticulosEdit extends javax.swing.JFrame {

    /**
     * Creates new form Conferencias
     */
    public ArticulosEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgTamano = new javax.swing.ButtonGroup();
        jpCabecera = new javax.swing.JPanel();
        lblConferencia = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jpDatosConfNueva = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblTema = new javax.swing.JLabel();
        lblTamano = new javax.swing.JLabel();
        lblAutores = new javax.swing.JLabel();
        jsNombre = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jsTema = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        jslAutores = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jpBotonesAutores = new javax.swing.JPanel();
        btnAnadirSesion = new javax.swing.JButton();
        btnBorrarSesion = new javax.swing.JButton();
        btnInfoSesion = new javax.swing.JButton();
        rbCorto = new javax.swing.JRadioButton();
        rbLargo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpCabecera.setBackground(new java.awt.Color(255, 204, 153));
        jpCabecera.setLayout(new java.awt.GridBagLayout());

        lblConferencia.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        lblConferencia.setText("Artículo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jpCabecera.add(lblConferencia, gridBagConstraints);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/guardar25.png"))); // NOI18N
        Guardar.setEnabled(false);
        Guardar.setMaximumSize(new java.awt.Dimension(25, 25));
        Guardar.setMinimumSize(new java.awt.Dimension(25, 25));
        Guardar.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jpCabecera.add(Guardar, gridBagConstraints);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/atras25.png"))); // NOI18N
        btnAtras.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAtras.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAtras.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jpCabecera.add(btnAtras, gridBagConstraints);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit25.png"))); // NOI18N
        btnEditar.setMaximumSize(new java.awt.Dimension(25, 25));
        btnEditar.setMinimumSize(new java.awt.Dimension(25, 25));
        btnEditar.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jpCabecera.add(btnEditar, gridBagConstraints);

        getContentPane().add(jpCabecera, java.awt.BorderLayout.PAGE_START);

        jpDatosConfNueva.setBackground(new java.awt.Color(204, 255, 153));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jpDatosConfNueva.setLayout(jPanel1Layout);

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblNombre, gridBagConstraints);

        lblTema.setText("Tema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblTema, gridBagConstraints);

        lblTamano.setText("Tamaño:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jpDatosConfNueva.add(lblTamano, gridBagConstraints);

        lblAutores.setText("Autores:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblAutores, gridBagConstraints);

        jsNombre.setViewportView(jEditorPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        jpDatosConfNueva.add(jsNombre, gridBagConstraints);

        jsTema.setViewportView(jEditorPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        jpDatosConfNueva.add(jsTema, gridBagConstraints);

        jslAutores.setPreferredSize(new java.awt.Dimension(150, 130));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jslAutores.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 0);
        jpDatosConfNueva.add(jslAutores, gridBagConstraints);

        jpBotonesAutores.setBackground(new java.awt.Color(255, 0, 153));
        jpBotonesAutores.setOpaque(false);
        jpBotonesAutores.setLayout(new java.awt.GridBagLayout());

        btnAnadirSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas25.png"))); // NOI18N
        btnAnadirSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.setOpaque(false);
        btnAnadirSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesAutores.add(btnAnadirSesion, gridBagConstraints);

        btnBorrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x25.png"))); // NOI18N
        btnBorrarSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.setOpaque(false);
        btnBorrarSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jpBotonesAutores.add(btnBorrarSesion, gridBagConstraints);

        btnInfoSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/i25.png"))); // NOI18N
        btnInfoSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.setOpaque(false);
        btnInfoSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesAutores.add(btnInfoSesion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jpDatosConfNueva.add(jpBotonesAutores, gridBagConstraints);

        bgTamano.add(rbCorto);
        rbCorto.setSelected(true);
        rbCorto.setText("Corto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 0);
        jpDatosConfNueva.add(rbCorto, gridBagConstraints);

        bgTamano.add(rbLargo);
        rbLargo.setText("Largo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 15);
        jpDatosConfNueva.add(rbLargo, gridBagConstraints);

        getContentPane().add(jpDatosConfNueva, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoSesionActionPerformed

    private void btnBorrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarSesionActionPerformed

    private void btnAnadirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticulosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticulosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticulosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticulosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArticulosEdit().setVisible(true);
            }
        });
    }

    public JButton getGuardar() {
        return Guardar;
    }

    public void setGuardar(JButton Guardar) {
        this.Guardar = Guardar;
    }

    public ButtonGroup getBgTamano() {
        return bgTamano;
    }

    public void setBgTamano(ButtonGroup bgTamano) {
        this.bgTamano = bgTamano;
    }

    public JButton getBtnAnadirSesion() {
        return btnAnadirSesion;
    }

    public void setBtnAnadirSesion(JButton btnAnadirSesion) {
        this.btnAnadirSesion = btnAnadirSesion;
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnBorrarSesion() {
        return btnBorrarSesion;
    }

    public void setBtnBorrarSesion(JButton btnBorrarSesion) {
        this.btnBorrarSesion = btnBorrarSesion;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnInfoSesion() {
        return btnInfoSesion;
    }

    public void setBtnInfoSesion(JButton btnInfoSesion) {
        this.btnInfoSesion = btnInfoSesion;
    }

    public JEditorPane getjEditorPane2() {
        return jEditorPane2;
    }

    public void setjEditorPane2(JEditorPane jEditorPane2) {
        this.jEditorPane2 = jEditorPane2;
    }

    public JEditorPane getjEditorPane3() {
        return jEditorPane3;
    }

    public void setjEditorPane3(JEditorPane jEditorPane3) {
        this.jEditorPane3 = jEditorPane3;
    }

    public JList<String> getjList1() {
        return jList1;
    }

    public void setjList1(JList<String> jList1) {
        this.jList1 = jList1;
    }

    public JPanel getJpBotonesAutores() {
        return jpBotonesAutores;
    }

    public void setJpBotonesAutores(JPanel jpBotonesAutores) {
        this.jpBotonesAutores = jpBotonesAutores;
    }

    public JPanel getJpCabecera() {
        return jpCabecera;
    }

    public void setJpCabecera(JPanel jpCabecera) {
        this.jpCabecera = jpCabecera;
    }

    public JPanel getJpDatosConfNueva() {
        return jpDatosConfNueva;
    }

    public void setJpDatosConfNueva(JPanel jpDatosConfNueva) {
        this.jpDatosConfNueva = jpDatosConfNueva;
    }

    public JScrollPane getJsNombre() {
        return jsNombre;
    }

    public void setJsNombre(JScrollPane jsNombre) {
        this.jsNombre = jsNombre;
    }

    public JScrollPane getJsTema() {
        return jsTema;
    }

    public void setJsTema(JScrollPane jsTema) {
        this.jsTema = jsTema;
    }

    public JScrollPane getJslAutores() {
        return jslAutores;
    }

    public void setJslAutores(JScrollPane jslAutores) {
        this.jslAutores = jslAutores;
    }

    public JLabel getLblAutores() {
        return lblAutores;
    }

    public void setLblAutores(JLabel lblAutores) {
        this.lblAutores = lblAutores;
    }

    public JLabel getLblConferencia() {
        return lblConferencia;
    }

    public void setLblConferencia(JLabel lblConferencia) {
        this.lblConferencia = lblConferencia;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblTamano() {
        return lblTamano;
    }

    public void setLblTamano(JLabel lblTamano) {
        this.lblTamano = lblTamano;
    }

    public JLabel getLblTema() {
        return lblTema;
    }

    public void setLblTema(JLabel lblTema) {
        this.lblTema = lblTema;
    }

    public JRadioButton getRbCorto() {
        return rbCorto;
    }

    public void setRbCorto(JRadioButton rbCorto) {
        this.rbCorto = rbCorto;
    }

    public JRadioButton getRbLargo() {
        return rbLargo;
    }

    public void setRbLargo(JRadioButton rbLargo) {
        this.rbLargo = rbLargo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.ButtonGroup bgTamano;
    private javax.swing.JButton btnAnadirSesion;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrarSesion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInfoSesion;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jpBotonesAutores;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPanel jpDatosConfNueva;
    private javax.swing.JScrollPane jsNombre;
    private javax.swing.JScrollPane jsTema;
    private javax.swing.JScrollPane jslAutores;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblConferencia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JLabel lblTema;
    private javax.swing.JRadioButton rbCorto;
    private javax.swing.JRadioButton rbLargo;
    // End of variables declaration//GEN-END:variables
}
