/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxectoaad;

import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author AnxoPregal
 */
public class Conferencias extends javax.swing.JFrame {

    /**
     * Creates new form Conferencias
     */
    public Conferencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpCabecera = new javax.swing.JPanel();
        lblConferencia = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jpDatosConfNueva = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTema = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jsId = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jsNombre = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jsTema = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        jsFechaInicio = new javax.swing.JScrollPane();
        jEditorPane4 = new javax.swing.JEditorPane();
        jsFechaFin = new javax.swing.JScrollPane();
        jEditorPane6 = new javax.swing.JEditorPane();
        jsHoraInicio = new javax.swing.JScrollPane();
        jEditorPane5 = new javax.swing.JEditorPane();
        jsHoraFin = new javax.swing.JScrollPane();
        jEditorPane8 = new javax.swing.JEditorPane();
        jsPrecio = new javax.swing.JScrollPane();
        jEditorPane9 = new javax.swing.JEditorPane();
        jsDescripcion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpCabecera.setBackground(new java.awt.Color(255, 204, 153));
        jpCabecera.setLayout(new java.awt.GridBagLayout());

        lblConferencia.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        lblConferencia.setText("Conferencia nueva");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jpCabecera.add(lblConferencia, gridBagConstraints);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/atras25.png"))); // NOI18N
        btnAtras.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAtras.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAtras.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jpCabecera.add(btnAtras, gridBagConstraints);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/guardar25.png"))); // NOI18N
        btnGuardar.setMaximumSize(new java.awt.Dimension(25, 25));
        btnGuardar.setMinimumSize(new java.awt.Dimension(25, 25));
        btnGuardar.setPreferredSize(new java.awt.Dimension(25, 25));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jpCabecera.add(btnGuardar, gridBagConstraints);

        getContentPane().add(jpCabecera, java.awt.BorderLayout.PAGE_START);

        jpDatosConfNueva.setBackground(new java.awt.Color(204, 255, 153));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpDatosConfNueva.setLayout(jPanel1Layout);

        lblId.setText("Id:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jpDatosConfNueva.add(lblId, gridBagConstraints);

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jpDatosConfNueva.add(lblNombre, gridBagConstraints);

        lblTema.setText("Tema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblTema, gridBagConstraints);

        lblFechaInicio.setText("Fecha inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblFechaInicio, gridBagConstraints);

        lblFechaFin.setText("Fecha Fin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblFechaFin, gridBagConstraints);

        lblHoraInicio.setText("Hora inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblHoraInicio, gridBagConstraints);

        lblHoraFin.setText("Hora de fin estipulada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblHoraFin, gridBagConstraints);

        lblPrecio.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblPrecio, gridBagConstraints);

        lblDescripcion.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 10, 0);
        jpDatosConfNueva.add(lblDescripcion, gridBagConstraints);

        jsId.setViewportView(jEditorPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        jpDatosConfNueva.add(jsId, gridBagConstraints);

        jsNombre.setViewportView(jEditorPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 15);
        jpDatosConfNueva.add(jsNombre, gridBagConstraints);

        jsTema.setViewportView(jEditorPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpDatosConfNueva.add(jsTema, gridBagConstraints);

        jsFechaInicio.setViewportView(jEditorPane4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpDatosConfNueva.add(jsFechaInicio, gridBagConstraints);

        jsFechaFin.setViewportView(jEditorPane6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 15);
        jpDatosConfNueva.add(jsFechaFin, gridBagConstraints);

        jsHoraInicio.setViewportView(jEditorPane5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpDatosConfNueva.add(jsHoraInicio, gridBagConstraints);

        jsHoraFin.setViewportView(jEditorPane8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 15);
        jpDatosConfNueva.add(jsHoraFin, gridBagConstraints);

        jsPrecio.setViewportView(jEditorPane9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 15);
        jpDatosConfNueva.add(jsPrecio, gridBagConstraints);

        jsDescripcion.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jsDescripcion.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 15);
        jpDatosConfNueva.add(jsDescripcion, gridBagConstraints);

        getContentPane().add(jpDatosConfNueva, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conferencias().setVisible(true);
            }
        });
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JEditorPane getjEditorPane1() {
        return jEditorPane1;
    }

    public void setjEditorPane1(JEditorPane jEditorPane1) {
        this.jEditorPane1 = jEditorPane1;
    }

    public JEditorPane getjEditorPane2() {
        return jEditorPane2;
    }

    public void setjEditorPane2(JEditorPane jEditorPane2) {
        this.jEditorPane2 = jEditorPane2;
    }

    public JEditorPane getjEditorPane3() {
        return jEditorPane3;
    }

    public void setjEditorPane3(JEditorPane jEditorPane3) {
        this.jEditorPane3 = jEditorPane3;
    }

    public JEditorPane getjEditorPane4() {
        return jEditorPane4;
    }

    public void setjEditorPane4(JEditorPane jEditorPane4) {
        this.jEditorPane4 = jEditorPane4;
    }

    public JEditorPane getjEditorPane5() {
        return jEditorPane5;
    }

    public void setjEditorPane5(JEditorPane jEditorPane5) {
        this.jEditorPane5 = jEditorPane5;
    }

    public JEditorPane getjEditorPane6() {
        return jEditorPane6;
    }

    public void setjEditorPane6(JEditorPane jEditorPane6) {
        this.jEditorPane6 = jEditorPane6;
    }

    public JEditorPane getjEditorPane8() {
        return jEditorPane8;
    }

    public void setjEditorPane8(JEditorPane jEditorPane8) {
        this.jEditorPane8 = jEditorPane8;
    }

    public JEditorPane getjEditorPane9() {
        return jEditorPane9;
    }

    public void setjEditorPane9(JEditorPane jEditorPane9) {
        this.jEditorPane9 = jEditorPane9;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JPanel getJpCabecera() {
        return jpCabecera;
    }

    public void setJpCabecera(JPanel jpCabecera) {
        this.jpCabecera = jpCabecera;
    }

    public JPanel getJpDatosConfNueva() {
        return jpDatosConfNueva;
    }

    public void setJpDatosConfNueva(JPanel jpDatosConfNueva) {
        this.jpDatosConfNueva = jpDatosConfNueva;
    }

    public JScrollPane getJsDescripcion() {
        return jsDescripcion;
    }

    public void setJsDescripcion(JScrollPane jsDescripcion) {
        this.jsDescripcion = jsDescripcion;
    }

    public JScrollPane getJsFechaFin() {
        return jsFechaFin;
    }

    public void setJsFechaFin(JScrollPane jsFechaFin) {
        this.jsFechaFin = jsFechaFin;
    }

    public JScrollPane getJsFechaInicio() {
        return jsFechaInicio;
    }

    public void setJsFechaInicio(JScrollPane jsFechaInicio) {
        this.jsFechaInicio = jsFechaInicio;
    }

    public JScrollPane getJsHoraFin() {
        return jsHoraFin;
    }

    public void setJsHoraFin(JScrollPane jsHoraFin) {
        this.jsHoraFin = jsHoraFin;
    }

    public JScrollPane getJsHoraInicio() {
        return jsHoraInicio;
    }

    public void setJsHoraInicio(JScrollPane jsHoraInicio) {
        this.jsHoraInicio = jsHoraInicio;
    }

    public JScrollPane getJsId() {
        return jsId;
    }

    public void setJsId(JScrollPane jsId) {
        this.jsId = jsId;
    }

    public JScrollPane getJsNombre() {
        return jsNombre;
    }

    public void setJsNombre(JScrollPane jsNombre) {
        this.jsNombre = jsNombre;
    }

    public JScrollPane getJsPrecio() {
        return jsPrecio;
    }

    public void setJsPrecio(JScrollPane jsPrecio) {
        this.jsPrecio = jsPrecio;
    }

    public JScrollPane getJsTema() {
        return jsTema;
    }

    public void setJsTema(JScrollPane jsTema) {
        this.jsTema = jsTema;
    }

    public JLabel getLblConferencia() {
        return lblConferencia;
    }

    public void setLblConferencia(JLabel lblConferencia) {
        this.lblConferencia = lblConferencia;
    }

    public JLabel getLblDescripcion() {
        return lblDescripcion;
    }

    public void setLblDescripcion(JLabel lblDescripcion) {
        this.lblDescripcion = lblDescripcion;
    }

    public JLabel getLblFechaFin() {
        return lblFechaFin;
    }

    public void setLblFechaFin(JLabel lblFechaFin) {
        this.lblFechaFin = lblFechaFin;
    }

    public JLabel getLblFechaInicio() {
        return lblFechaInicio;
    }

    public void setLblFechaInicio(JLabel lblFechaInicio) {
        this.lblFechaInicio = lblFechaInicio;
    }

    public JLabel getLblHoraFin() {
        return lblHoraFin;
    }

    public void setLblHoraFin(JLabel lblHoraFin) {
        this.lblHoraFin = lblHoraFin;
    }

    public JLabel getLblHoraInicio() {
        return lblHoraInicio;
    }

    public void setLblHoraInicio(JLabel lblHoraInicio) {
        this.lblHoraInicio = lblHoraInicio;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblPrecio() {
        return lblPrecio;
    }

    public void setLblPrecio(JLabel lblPrecio) {
        this.lblPrecio = lblPrecio;
    }

    public JLabel getLblTema() {
        return lblTema;
    }

    public void setLblTema(JLabel lblTema) {
        this.lblTema = lblTema;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JEditorPane jEditorPane4;
    private javax.swing.JEditorPane jEditorPane5;
    private javax.swing.JEditorPane jEditorPane6;
    private javax.swing.JEditorPane jEditorPane8;
    private javax.swing.JEditorPane jEditorPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPanel jpDatosConfNueva;
    private javax.swing.JScrollPane jsDescripcion;
    private javax.swing.JScrollPane jsFechaFin;
    private javax.swing.JScrollPane jsFechaInicio;
    private javax.swing.JScrollPane jsHoraFin;
    private javax.swing.JScrollPane jsHoraInicio;
    private javax.swing.JScrollPane jsId;
    private javax.swing.JScrollPane jsNombre;
    private javax.swing.JScrollPane jsPrecio;
    private javax.swing.JScrollPane jsTema;
    private javax.swing.JLabel lblConferencia;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTema;
    // End of variables declaration//GEN-END:variables
}
