/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxectoaad;

import javax.swing.JFrame;
import javax.swing.ListCellRenderer;

/**
 *
 * @author AnxoPregal
 */
public class jfPruebas extends javax.swing.JFrame {

    /**
     * Creates new form jfListConf
     */
    public jfPruebas() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ListCellRenderer a;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jpGestionFondo = new javax.swing.JPanel();
        jpCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jpConferencias = new javax.swing.JPanel();
        lblListado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListConfe = new javax.swing.JList<>();
        jpBotones = new javax.swing.JPanel();
        btnAnadir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jpInfo = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        jpInfoConfe = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        lblNSesiones = new javax.swing.JLabel();
        lblNParticipantes = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpSesiones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnadir1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnBorrar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jpParticipantes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAnadir4 = new javax.swing.JButton();
        btnEditar4 = new javax.swing.JButton();
        btnBorrar4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de conferencias");
        setMinimumSize(new java.awt.Dimension(800, 550));

        jpGestionFondo.setBackground(new java.awt.Color(204, 255, 153));
        jpGestionFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jpGestionFondo.setToolTipText("");
        jpGestionFondo.setMinimumSize(new java.awt.Dimension(300, 300));
        jpGestionFondo.setLayout(new java.awt.GridBagLayout());

        jpCabecera.setBackground(new java.awt.Color(255, 204, 153));
        jpCabecera.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        lblTitulo.setText("GESTIÓN DE CONFERENCIAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(22, 60, 20, 55);
        jpCabecera.add(lblTitulo, gridBagConstraints);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/atras40.png"))); // NOI18N
        btnAtras.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAtras.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAtras.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jpCabecera.add(btnAtras, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jpGestionFondo.add(jpCabecera, gridBagConstraints);

        java.awt.GridBagLayout jpConferenciasLayout = new java.awt.GridBagLayout();
        jpConferenciasLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jpConferenciasLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpConferencias.setLayout(jpConferenciasLayout);

        lblListado.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblListado.setText("Listado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jpConferencias.add(lblListado, gridBagConstraints);

        jScrollPane1.setBorder(null);

        jListConfe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jListConfe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListConfe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListConfe.setToolTipText("");
        jListConfe.setAlignmentX(10.5F);
        jListConfe.setAlignmentY(10.5F);
        jListConfe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListConfeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListConfe);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jpConferencias.add(jScrollPane1, gridBagConstraints);

        jpBotones.setBackground(new java.awt.Color(255, 0, 153));
        jpBotones.setOpaque(false);
        jpBotones.setPreferredSize(new java.awt.Dimension(40, 160));
        jpBotones.setLayout(new java.awt.GridBagLayout());

        btnAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas40.png"))); // NOI18N
        btnAnadir.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAnadir.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAnadir.setOpaque(false);
        btnAnadir.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotones.add(btnAnadir, gridBagConstraints);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit40.png"))); // NOI18N
        btnEditar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnEditar.setMinimumSize(new java.awt.Dimension(40, 40));
        btnEditar.setOpaque(false);
        btnEditar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jpBotones.add(btnEditar, gridBagConstraints);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x40.png"))); // NOI18N
        btnBorrar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnBorrar.setMinimumSize(new java.awt.Dimension(40, 40));
        btnBorrar.setOpaque(false);
        btnBorrar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotones.add(btnBorrar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -20;
        jpConferencias.add(jpBotones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jpGestionFondo.add(jpConferencias, gridBagConstraints);

        jpInfo.setLayout(new java.awt.GridBagLayout());

        lblInfo.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblInfo.setText("Información conferencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        jpInfo.add(lblInfo, gridBagConstraints);

        jpInfoConfe.setBackground(new java.awt.Color(255, 255, 255));
        jpInfoConfe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpInfoConfe.setPreferredSize(new java.awt.Dimension(100, 100));
        java.awt.GridBagLayout jpInfoConfeLayout = new java.awt.GridBagLayout();
        jpInfoConfeLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jpInfoConfeLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpInfoConfe.setLayout(jpInfoConfeLayout);

        lbl1.setText("Fecha conferencia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jpInfoConfe.add(lbl1, gridBagConstraints);

        lbl2.setText("Hora inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jpInfoConfe.add(lbl2, gridBagConstraints);

        lbl3.setText("Nº de sesiones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jpInfoConfe.add(lbl3, gridBagConstraints);

        lbl4.setText("Nº de participantes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jpInfoConfe.add(lbl4, gridBagConstraints);

        lbl5.setText("Hora de fin estipulada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jpInfoConfe.add(lbl5, gridBagConstraints);

        lbl6.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jpInfoConfe.add(lbl6, gridBagConstraints);

        lbl7.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 5, 20);
        jpInfoConfe.add(lbl7, gridBagConstraints);

        lblFecha.setText(" ");
        lblFecha.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jpInfoConfe.add(lblFecha, gridBagConstraints);

        lblHoraInicio.setText(" ");
        lblHoraInicio.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jpInfoConfe.add(lblHoraInicio, gridBagConstraints);

        lblNSesiones.setText(" ");
        lblNSesiones.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jpInfoConfe.add(lblNSesiones, gridBagConstraints);

        lblNParticipantes.setText(" ");
        lblNParticipantes.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jpInfoConfe.add(lblNParticipantes, gridBagConstraints);

        lblHoraFin.setText(" ");
        lblHoraFin.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jpInfoConfe.add(lblHoraFin, gridBagConstraints);

        lblPrecio.setText(" ");
        lblPrecio.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jpInfoConfe.add(lblPrecio, gridBagConstraints);

        lblDescripcion.setText(" ");
        lblDescripcion.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jpInfoConfe.add(lblDescripcion, gridBagConstraints);

        jLabel6.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 20);
        jpInfoConfe.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Temas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 20);
        jpInfoConfe.add(jLabel7, gridBagConstraints);

        jLabel8.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpInfoConfe.add(jLabel8, gridBagConstraints);

        jLabel9.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpInfoConfe.add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 427;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        jpInfo.add(jpInfoConfe, gridBagConstraints);

        jpSesiones.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sesiones");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jpSesiones.add(jLabel1, gridBagConstraints);

        btnAnadir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas40.png"))); // NOI18N
        btnAnadir1.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAnadir1.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAnadir1.setOpaque(false);
        btnAnadir1.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAnadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jpSesiones.add(btnAnadir1, gridBagConstraints);

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit40.png"))); // NOI18N
        btnEditar1.setMaximumSize(new java.awt.Dimension(40, 40));
        btnEditar1.setMinimumSize(new java.awt.Dimension(40, 40));
        btnEditar1.setOpaque(false);
        btnEditar1.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jpSesiones.add(btnEditar1, gridBagConstraints);

        btnBorrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x40.png"))); // NOI18N
        btnBorrar1.setMaximumSize(new java.awt.Dimension(40, 40));
        btnBorrar1.setMinimumSize(new java.awt.Dimension(40, 40));
        btnBorrar1.setOpaque(false);
        btnBorrar1.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jpSesiones.add(btnBorrar1, gridBagConstraints);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setPreferredSize(new java.awt.Dimension(100, 80));
        jScrollPane2.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jpSesiones.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        jpInfo.add(jpSesiones, gridBagConstraints);

        jpParticipantes.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Participantes");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jpParticipantes.add(jLabel4, gridBagConstraints);

        btnAnadir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas40.png"))); // NOI18N
        btnAnadir4.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAnadir4.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAnadir4.setOpaque(false);
        btnAnadir4.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAnadir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jpParticipantes.add(btnAnadir4, gridBagConstraints);

        btnEditar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit40.png"))); // NOI18N
        btnEditar4.setMaximumSize(new java.awt.Dimension(40, 40));
        btnEditar4.setMinimumSize(new java.awt.Dimension(40, 40));
        btnEditar4.setOpaque(false);
        btnEditar4.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEditar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jpParticipantes.add(btnEditar4, gridBagConstraints);

        btnBorrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x40.png"))); // NOI18N
        btnBorrar4.setMaximumSize(new java.awt.Dimension(40, 40));
        btnBorrar4.setMinimumSize(new java.awt.Dimension(40, 40));
        btnBorrar4.setOpaque(false);
        btnBorrar4.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBorrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jpParticipantes.add(btnBorrar4, gridBagConstraints);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jList3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jpParticipantes.add(jScrollPane4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        jpInfo.add(jpParticipantes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jpGestionFondo.add(jpInfo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpGestionFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpGestionFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jListConfeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListConfeMouseClicked
        // TODO add your handling code here:
        System.out.println(this.jListConfe.getSelectedValue());
    }//GEN-LAST:event_jListConfeMouseClicked

    private void btnAnadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadir1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnAnadir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadir4ActionPerformed

    private void btnEditar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar4ActionPerformed

    private void btnBorrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnAnadir1;
    private javax.swing.JButton btnAnadir4;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar4;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jListConfe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPanel jpConferencias;
    private javax.swing.JPanel jpGestionFondo;
    private javax.swing.JPanel jpInfo;
    private javax.swing.JPanel jpInfoConfe;
    private javax.swing.JPanel jpParticipantes;
    private javax.swing.JPanel jpSesiones;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblListado;
    private javax.swing.JLabel lblNParticipantes;
    private javax.swing.JLabel lblNSesiones;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
