/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxectoaad;

import java.text.DateFormat;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;
import oracle.jrockit.jfr.tools.ConCatRepository;
import pojos.Conferencia;

/**
 *
 * @author AnxoPregal
 */
public class jfPruebas1 extends javax.swing.JFrame {
    
    /**
     * Creates new form jfListConf
     */    
    public jfPruebas1() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ListCellRenderer a;
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jpGestionFondo = new javax.swing.JPanel();
        jpCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jpConferencias = new javax.swing.JPanel();
        lblListado = new javax.swing.JLabel();
        jScrollPaneConfe = new javax.swing.JScrollPane();
        jListConfe = new javax.swing.JList<>();
        jpBotonesConfe = new javax.swing.JPanel();
        btnAnadirConfe = new javax.swing.JButton();
        btnEditarConfe = new javax.swing.JButton();
        btnBorrarConfe = new javax.swing.JButton();
        jpInfo = new javax.swing.JPanel();
        jpInfoConfe = new javax.swing.JPanel();
        lblInfoConfe = new javax.swing.JLabel();
        jpInfoConfeContenido = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblTema = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        lblNSesiones = new javax.swing.JLabel();
        lblNParticipantes = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblNombreEdit = new javax.swing.JLabel();
        lblTemaEdit = new javax.swing.JLabel();
        lblFechaEdit = new javax.swing.JLabel();
        lblHoraInicioEdit = new javax.swing.JLabel();
        lblNSesionesEdit = new javax.swing.JLabel();
        lblNParticipantesEdit = new javax.swing.JLabel();
        lblHoraFinEdit = new javax.swing.JLabel();
        lblPrecioEdit = new javax.swing.JLabel();
        lblDescripcionEdit = new javax.swing.JLabel();
        jpSesiones = new javax.swing.JPanel();
        lblSesiones = new javax.swing.JLabel();
        jScrollPaneSesiones = new javax.swing.JScrollPane();
        jListSesiones = new javax.swing.JList<>();
        jpBotonesSesiones = new javax.swing.JPanel();
        btnAnadirSesion = new javax.swing.JButton();
        btnBorrarSesion = new javax.swing.JButton();
        btnInfoSesion = new javax.swing.JButton();
        jpParticipantes = new javax.swing.JPanel();
        lblParticipantes = new javax.swing.JLabel();
        jScrollPaneParticipantes = new javax.swing.JScrollPane();
        jListParticipantes = new javax.swing.JList<>();
        jpBotonesParticipantes = new javax.swing.JPanel();
        btnAnadirParticipante = new javax.swing.JButton();
        btnBorrarParticipante = new javax.swing.JButton();
        btnInfoParticipante = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de conferencias");
        setMinimumSize(new java.awt.Dimension(800, 550));

        jpGestionFondo.setBackground(new java.awt.Color(204, 255, 153));
        jpGestionFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jpGestionFondo.setToolTipText("");
        jpGestionFondo.setMinimumSize(new java.awt.Dimension(300, 300));
        jpGestionFondo.setLayout(new java.awt.GridBagLayout());

        jpCabecera.setBackground(new java.awt.Color(255, 204, 153));
        jpCabecera.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        lblTitulo.setText("GESTIÓN DE CONFERENCIAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(22, 60, 20, 55);
        jpCabecera.add(lblTitulo, gridBagConstraints);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/atras25.png"))); // NOI18N
        btnAtras.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAtras.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAtras.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jpCabecera.add(btnAtras, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jpGestionFondo.add(jpCabecera, gridBagConstraints);

        java.awt.GridBagLayout jpConferenciasLayout = new java.awt.GridBagLayout();
        jpConferenciasLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jpConferenciasLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpConferencias.setLayout(jpConferenciasLayout);

        lblListado.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblListado.setText("Conferencias");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jpConferencias.add(lblListado, gridBagConstraints);

        jScrollPaneConfe.setBorder(null);

        jListConfe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jListConfe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListConfe.setToolTipText("");
        jListConfe.setAlignmentX(10.5F);
        jListConfe.setAlignmentY(10.5F);
        jListConfe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListConfeMouseClicked(evt);
            }
        });
        jScrollPaneConfe.setViewportView(jListConfe);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jpConferencias.add(jScrollPaneConfe, gridBagConstraints);

        jpBotonesConfe.setBackground(new java.awt.Color(255, 0, 153));
        jpBotonesConfe.setOpaque(false);
        jpBotonesConfe.setPreferredSize(new java.awt.Dimension(40, 160));
        jpBotonesConfe.setLayout(new java.awt.GridBagLayout());

        btnAnadirConfe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas25.png"))); // NOI18N
        btnAnadirConfe.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAnadirConfe.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAnadirConfe.setOpaque(false);
        btnAnadirConfe.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAnadirConfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirConfeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesConfe.add(btnAnadirConfe, gridBagConstraints);

        btnEditarConfe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit25.png"))); // NOI18N
        btnEditarConfe.setMaximumSize(new java.awt.Dimension(25, 25));
        btnEditarConfe.setMinimumSize(new java.awt.Dimension(25, 25));
        btnEditarConfe.setOpaque(false);
        btnEditarConfe.setPreferredSize(new java.awt.Dimension(25, 25));
        btnEditarConfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarConfeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jpBotonesConfe.add(btnEditarConfe, gridBagConstraints);

        btnBorrarConfe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x25.png"))); // NOI18N
        btnBorrarConfe.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBorrarConfe.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBorrarConfe.setOpaque(false);
        btnBorrarConfe.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBorrarConfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarConfeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesConfe.add(btnBorrarConfe, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -20;
        jpConferencias.add(jpBotonesConfe, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jpGestionFondo.add(jpConferencias, gridBagConstraints);

        jpInfo.setLayout(new java.awt.GridBagLayout());

        jpInfoConfe.setLayout(new java.awt.GridBagLayout());

        lblInfoConfe.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblInfoConfe.setText("Información conferencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jpInfoConfe.add(lblInfoConfe, gridBagConstraints);

        jpInfoConfeContenido.setBackground(new java.awt.Color(255, 255, 255));
        jpInfoConfeContenido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpInfoConfeContenido.setPreferredSize(new java.awt.Dimension(100, 100));
        java.awt.GridBagLayout jpInfoConfeLayout = new java.awt.GridBagLayout();
        jpInfoConfeLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jpInfoConfeLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpInfoConfeContenido.setLayout(jpInfoConfeLayout);

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 1, 20);
        jpInfoConfeContenido.add(lblNombre, gridBagConstraints);

        lblTema.setText("Tema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 1, 20);
        jpInfoConfeContenido.add(lblTema, gridBagConstraints);

        lblFecha.setText("Fecha conferencia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jpInfoConfeContenido.add(lblFecha, gridBagConstraints);

        lblHoraInicio.setText("Hora inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jpInfoConfeContenido.add(lblHoraInicio, gridBagConstraints);

        lblNSesiones.setText("Nº de sesiones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jpInfoConfeContenido.add(lblNSesiones, gridBagConstraints);

        lblNParticipantes.setText("Nº de participantes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jpInfoConfeContenido.add(lblNParticipantes, gridBagConstraints);

        lblHoraFin.setText("Hora de fin estipulada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jpInfoConfeContenido.add(lblHoraFin, gridBagConstraints);

        lblPrecio.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jpInfoConfeContenido.add(lblPrecio, gridBagConstraints);

        lblDescripcion.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 5, 20);
        jpInfoConfeContenido.add(lblDescripcion, gridBagConstraints);

        lblNombreEdit.setText("                   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 1, 1, 1);
        jpInfoConfeContenido.add(lblNombreEdit, gridBagConstraints);

        lblTemaEdit.setText("             ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 1, 1, 1);
        jpInfoConfeContenido.add(lblTemaEdit, gridBagConstraints);

        lblFechaEdit.setText("                   ");
        lblFechaEdit.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jpInfoConfeContenido.add(lblFechaEdit, gridBagConstraints);

        lblHoraInicioEdit.setText(" ");
        lblHoraInicioEdit.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jpInfoConfeContenido.add(lblHoraInicioEdit, gridBagConstraints);

        lblNSesionesEdit.setText(" ");
        lblNSesionesEdit.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jpInfoConfeContenido.add(lblNSesionesEdit, gridBagConstraints);

        lblNParticipantesEdit.setText(" ");
        lblNParticipantesEdit.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jpInfoConfeContenido.add(lblNParticipantesEdit, gridBagConstraints);

        lblHoraFinEdit.setText(" ");
        lblHoraFinEdit.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jpInfoConfeContenido.add(lblHoraFinEdit, gridBagConstraints);

        lblPrecioEdit.setText(" ");
        lblPrecioEdit.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jpInfoConfeContenido.add(lblPrecioEdit, gridBagConstraints);

        lblDescripcionEdit.setText(" ");
        lblDescripcionEdit.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 5, 1);
        jpInfoConfeContenido.add(lblDescripcionEdit, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        jpInfoConfe.add(jpInfoConfeContenido, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jpInfo.add(jpInfoConfe, gridBagConstraints);

        java.awt.GridBagLayout jpConferencias1Layout = new java.awt.GridBagLayout();
        jpConferencias1Layout.columnWidths = new int[] {0, 5, 0};
        jpConferencias1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpSesiones.setLayout(jpConferencias1Layout);

        lblSesiones.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblSesiones.setText("Sesiones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jpSesiones.add(lblSesiones, gridBagConstraints);

        jScrollPaneSesiones.setBorder(null);

        jListSesiones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jListSesiones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSesiones.setToolTipText("");
        jListSesiones.setAlignmentX(10.5F);
        jListSesiones.setAlignmentY(10.5F);
        jListSesiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSesionesMouseClicked(evt);
            }
        });
        jScrollPaneSesiones.setViewportView(jListSesiones);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jpSesiones.add(jScrollPaneSesiones, gridBagConstraints);

        jpBotonesSesiones.setBackground(new java.awt.Color(255, 0, 153));
        jpBotonesSesiones.setOpaque(false);
        jpBotonesSesiones.setLayout(new java.awt.GridBagLayout());

        btnAnadirSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas25.png"))); // NOI18N
        btnAnadirSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.setOpaque(false);
        btnAnadirSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesSesiones.add(btnAnadirSesion, gridBagConstraints);

        btnBorrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x25.png"))); // NOI18N
        btnBorrarSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.setOpaque(false);
        btnBorrarSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jpBotonesSesiones.add(btnBorrarSesion, gridBagConstraints);

        btnInfoSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/i25.png"))); // NOI18N
        btnInfoSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.setOpaque(false);
        btnInfoSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesSesiones.add(btnInfoSesion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -20;
        jpSesiones.add(jpBotonesSesiones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jpInfo.add(jpSesiones, gridBagConstraints);

        java.awt.GridBagLayout jpConferencias2Layout = new java.awt.GridBagLayout();
        jpConferencias2Layout.columnWidths = new int[] {0, 5, 0};
        jpConferencias2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpParticipantes.setLayout(jpConferencias2Layout);

        lblParticipantes.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblParticipantes.setText("Participantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jpParticipantes.add(lblParticipantes, gridBagConstraints);

        jScrollPaneParticipantes.setBorder(null);

        jListParticipantes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jListParticipantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListParticipantes.setToolTipText("");
        jListParticipantes.setAlignmentX(10.5F);
        jListParticipantes.setAlignmentY(10.5F);
        jListParticipantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListParticipantesMouseClicked(evt);
            }
        });
        jScrollPaneParticipantes.setViewportView(jListParticipantes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jpParticipantes.add(jScrollPaneParticipantes, gridBagConstraints);

        jpBotonesParticipantes.setBackground(new java.awt.Color(255, 0, 153));
        jpBotonesParticipantes.setOpaque(false);
        jpBotonesParticipantes.setLayout(new java.awt.GridBagLayout());

        btnAnadirParticipante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas25.png"))); // NOI18N
        btnAnadirParticipante.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAnadirParticipante.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAnadirParticipante.setOpaque(false);
        btnAnadirParticipante.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAnadirParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirParticipanteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesParticipantes.add(btnAnadirParticipante, gridBagConstraints);

        btnBorrarParticipante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x25.png"))); // NOI18N
        btnBorrarParticipante.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBorrarParticipante.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBorrarParticipante.setOpaque(false);
        btnBorrarParticipante.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBorrarParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarParticipanteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jpBotonesParticipantes.add(btnBorrarParticipante, gridBagConstraints);

        btnInfoParticipante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/i25.png"))); // NOI18N
        btnInfoParticipante.setMaximumSize(new java.awt.Dimension(25, 25));
        btnInfoParticipante.setMinimumSize(new java.awt.Dimension(25, 25));
        btnInfoParticipante.setOpaque(false);
        btnInfoParticipante.setPreferredSize(new java.awt.Dimension(25, 25));
        btnInfoParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoParticipanteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesParticipantes.add(btnInfoParticipante, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -20;
        jpParticipantes.add(jpBotonesParticipantes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jpInfo.add(jpParticipantes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jpGestionFondo.add(jpInfo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpGestionFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpGestionFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAnadirConfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirConfeActionPerformed
        Conferencias conferencia = new Conferencias();
        conferencia.setVisible(true);
    }//GEN-LAST:event_btnAnadirConfeActionPerformed

    private void btnEditarConfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarConfeActionPerformed
        
    }//GEN-LAST:event_btnEditarConfeActionPerformed

    private void btnBorrarConfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarConfeActionPerformed
        
    }//GEN-LAST:event_btnBorrarConfeActionPerformed

    private void jListConfeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListConfeMouseClicked
        // TODO add your handling code here:
        DateFormat df = DateFormat.getDateInstance();
        Object obj = this.jListConfe.getSelectedValue();
        System.out.println(obj);
        if (obj != null) {
            if (obj instanceof hmapasinversa.Conferencias) {
                hmapasinversa.Conferencias confe = (hmapasinversa.Conferencias)obj;
                lblNombreEdit.setText(confe.getNombre());
                lblFechaEdit.setText(df.format(confe.getFechaHoraInicio()));
                lblNSesionesEdit.setText(confe.getSesioneses().size()+"");
                lblHoraFinEdit.setText(df.format(confe.getFechaHoraInicio()));
                lblDescripcionEdit.setText(confe.getNombre());
                lblTemaEdit.setText(confe.getNombre());
                lblHoraInicioEdit.setText(df.format(confe.getFechaHoraInicio()));
                lblNParticipantesEdit.setText(confe.getParticipantesConferenciases().size()+"");
                lblPrecioEdit.setText(confe.getPrecio()+"");
            }
        }
    }//GEN-LAST:event_jListConfeMouseClicked

    private void jListSesionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSesionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListSesionesMouseClicked

    private void btnAnadirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirSesionActionPerformed

    private void btnBorrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarSesionActionPerformed

    private void jListParticipantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListParticipantesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListParticipantesMouseClicked

    private void btnAnadirParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirParticipanteActionPerformed

    private void btnBorrarParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarParticipanteActionPerformed

    private void btnInfoSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoSesionActionPerformed

    private void btnInfoParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoParticipanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPruebas1().setVisible(true);
            }
        });
    }

    public JButton getBtnAnadirConfe() {
        return btnAnadirConfe;
    }

    public void setBtnAnadirConfe(JButton btnAnadirConfe) {
        this.btnAnadirConfe = btnAnadirConfe;
    }

    public JButton getBtnAnadirParticipante() {
        return btnAnadirParticipante;
    }

    public void setBtnAnadirParticipante(JButton btnAnadirParticipante) {
        this.btnAnadirParticipante = btnAnadirParticipante;
    }

    public JButton getBtnAnadirSesion() {
        return btnAnadirSesion;
    }

    public void setBtnAnadirSesion(JButton btnAnadirSesion) {
        this.btnAnadirSesion = btnAnadirSesion;
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnBorrarConfe() {
        return btnBorrarConfe;
    }

    public void setBtnBorrarConfe(JButton btnBorrarConfe) {
        this.btnBorrarConfe = btnBorrarConfe;
    }

    public JButton getBtnBorrarParticipante() {
        return btnBorrarParticipante;
    }

    public void setBtnBorrarParticipante(JButton btnBorrarParticipante) {
        this.btnBorrarParticipante = btnBorrarParticipante;
    }

    public JButton getBtnBorrarSesion() {
        return btnBorrarSesion;
    }

    public void setBtnBorrarSesion(JButton btnBorrarSesion) {
        this.btnBorrarSesion = btnBorrarSesion;
    }

    public JButton getBtnEditarConfe() {
        return btnEditarConfe;
    }

    public void setBtnEditarConfe(JButton btnEditarConfe) {
        this.btnEditarConfe = btnEditarConfe;
    }

    public JButton getBtnInfoParticipante() {
        return btnInfoParticipante;
    }

    public void setBtnInfoParticipante(JButton btnInfoParticipante) {
        this.btnInfoParticipante = btnInfoParticipante;
    }

    public JButton getBtnInfoSesion() {
        return btnInfoSesion;
    }

    public void setBtnInfoSesion(JButton btnInfoSesion) {
        this.btnInfoSesion = btnInfoSesion;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JList<String> getjListConfe() {
        return jListConfe;
    }

    public void setjListConfe(JList<String> jListConfe) {
        this.jListConfe = jListConfe;
    }

    public JList<String> getjListParticipantes() {
        return jListParticipantes;
    }

    public void setjListParticipantes(JList<String> jListParticipantes) {
        this.jListParticipantes = jListParticipantes;
    }

    public JList<String> getjListSesiones() {
        return jListSesiones;
    }

    public void setjListSesiones(JList<String> jListSesiones) {
        this.jListSesiones = jListSesiones;
    }

    public JScrollPane getjScrollPaneConfe() {
        return jScrollPaneConfe;
    }

    public void setjScrollPaneConfe(JScrollPane jScrollPaneConfe) {
        this.jScrollPaneConfe = jScrollPaneConfe;
    }

    public JScrollPane getjScrollPaneParticipantes() {
        return jScrollPaneParticipantes;
    }

    public void setjScrollPaneParticipantes(JScrollPane jScrollPaneParticipantes) {
        this.jScrollPaneParticipantes = jScrollPaneParticipantes;
    }

    public JScrollPane getjScrollPaneSesiones() {
        return jScrollPaneSesiones;
    }

    public void setjScrollPaneSesiones(JScrollPane jScrollPaneSesiones) {
        this.jScrollPaneSesiones = jScrollPaneSesiones;
    }

    public JPanel getJpBotonesConfe() {
        return jpBotonesConfe;
    }

    public void setJpBotonesConfe(JPanel jpBotonesConfe) {
        this.jpBotonesConfe = jpBotonesConfe;
    }

    public JPanel getJpBotonesParticipantes() {
        return jpBotonesParticipantes;
    }

    public void setJpBotonesParticipantes(JPanel jpBotonesParticipantes) {
        this.jpBotonesParticipantes = jpBotonesParticipantes;
    }

    public JPanel getJpBotonesSesiones() {
        return jpBotonesSesiones;
    }

    public void setJpBotonesSesiones(JPanel jpBotonesSesiones) {
        this.jpBotonesSesiones = jpBotonesSesiones;
    }

    public JPanel getJpCabecera() {
        return jpCabecera;
    }

    public void setJpCabecera(JPanel jpCabecera) {
        this.jpCabecera = jpCabecera;
    }

    public JPanel getJpConferencias() {
        return jpConferencias;
    }

    public void setJpConferencias(JPanel jpConferencias) {
        this.jpConferencias = jpConferencias;
    }

    public JPanel getJpGestionFondo() {
        return jpGestionFondo;
    }

    public void setJpGestionFondo(JPanel jpGestionFondo) {
        this.jpGestionFondo = jpGestionFondo;
    }

    public JPanel getJpInfo() {
        return jpInfo;
    }

    public void setJpInfo(JPanel jpInfo) {
        this.jpInfo = jpInfo;
    }

    public JPanel getJpInfoConfe() {
        return jpInfoConfe;
    }

    public void setJpInfoConfe(JPanel jpInfoConfe) {
        this.jpInfoConfe = jpInfoConfe;
    }

    public JPanel getJpInfoConfeContenido() {
        return jpInfoConfeContenido;
    }

    public void setJpInfoConfeContenido(JPanel jpInfoConfeContenido) {
        this.jpInfoConfeContenido = jpInfoConfeContenido;
    }

    public JPanel getJpParticipantes() {
        return jpParticipantes;
    }

    public void setJpParticipantes(JPanel jpParticipantes) {
        this.jpParticipantes = jpParticipantes;
    }

    public JPanel getJpSesiones() {
        return jpSesiones;
    }

    public void setJpSesiones(JPanel jpSesiones) {
        this.jpSesiones = jpSesiones;
    }

    public JLabel getLblDescripcion() {
        return lblDescripcion;
    }

    public void setLblDescripcion(String text) {
        this.lblDescripcion.setText(text);
    }

    public JLabel getLblDescripcionEdit() {
        return lblDescripcionEdit;
    }

    public void setLblDescripcionEdit(String text) {
        this.lblDescripcionEdit.setText(text);
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(String text) {
        this.lblFecha.setText(text);
    }

    public JLabel getLblFechaEdit() {
        return lblFechaEdit;
    }

    public void setLblFechaEdit(String text) {
        this.lblFechaEdit.setText(text);
    }

    public JLabel getLblHoraFin() {
        return lblHoraFin;
    }

    public void setLblHoraFin(String text) {
        this.lblHoraFin.setText(text);
    }

    public JLabel getLblHoraFinEdit() {
        return lblHoraFinEdit;
    }

    public void setLblHoraFinEdit(String text) {
        this.lblHoraFinEdit.setText(text);
    }

    public JLabel getLblHoraInicio() {
        return lblHoraInicio;
    }

    public void setLblHoraInicio(String text) {
        this.lblHoraInicio.setText(text);
    }

    public JLabel getLblHoraInicioEdit() {
        return lblHoraInicioEdit;
    }

    public void setLblHoraInicioEdit(String text) {
        this.lblHoraInicioEdit.setText(text);
    }

    public JLabel getLblInfoConfe() {
        return lblInfoConfe;
    }

    public void setLblInfoConfe(String text) {
        this.lblInfoConfe.setText(text);
    }

    public JLabel getLblListado() {
        return lblListado;
    }

    public void setLblListado(String text) {
        this.lblListado.setText(text);
    }

    public JLabel getLblNParticipantes() {
        return lblNParticipantes;
    }

    public void setLblNParticipantes(String text) {
        this.lblNParticipantes.setText(text);
    }

    public JLabel getLblNParticipantesEdit() {
        return lblNParticipantesEdit;
    }

    public void setLblNParticipantesEdit(String text) {
        this.lblNParticipantesEdit.setText(text);
    }

    public JLabel getLblNSesiones() {
        return lblNSesiones;
    }

    public void setLblNSesiones(String text) {
        this.lblNSesiones.setText(text);
    }

    public JLabel getLblNSesionesEdit() {
        return lblNSesionesEdit;
    }

    public void setLblNSesionesEdit(String text) {
        this.lblNSesionesEdit.setText(text);
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(String text) {
        this.lblNombre.setText(text);
    }

    public JLabel getLblNombreEdit() {
        return lblNombreEdit;
    }

    public void setLblNombreEdit(String text) {
        this.lblNombreEdit.setText(text);
    }

    public JLabel getLblParticipantes() {
        return lblParticipantes;
    }

    public void setLblParticipantes(String text) {
        this.lblParticipantes.setText(text);
    }

    public JLabel getLblPrecio() {
        return lblPrecio;
    }

    public void setLblPrecio(String text) {
        this.lblPrecio.setText(text);
    }

    public JLabel getLblPrecioEdit() {
        return lblPrecioEdit;
    }

    public void setLblPrecioEdit(String text) {
        this.lblPrecioEdit.setText(text);
    }

    public JLabel getLblSesiones() {
        return lblSesiones;
    }

    public void setLblSesiones(String text) {
        this.lblSesiones.setText(text);
    }

    public JLabel getLblTema() {
        return lblTema;
    }

    public void setLblTema(String text) {
        this.lblTema.setText(text);
    }

    public JLabel getLblTemaEdit() {
        return lblTemaEdit;
    }

    public void setLblTemaEdit(String text) {
        this.lblTemaEdit.setText(text);
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(String text) {
        this.lblTitulo.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirConfe;
    private javax.swing.JButton btnAnadirParticipante;
    private javax.swing.JButton btnAnadirSesion;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrarConfe;
    private javax.swing.JButton btnBorrarParticipante;
    private javax.swing.JButton btnBorrarSesion;
    private javax.swing.JButton btnEditarConfe;
    private javax.swing.JButton btnInfoParticipante;
    private javax.swing.JButton btnInfoSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListConfe;
    private javax.swing.JList<String> jListParticipantes;
    private javax.swing.JList<String> jListSesiones;
    private javax.swing.JScrollPane jScrollPaneConfe;
    private javax.swing.JScrollPane jScrollPaneParticipantes;
    private javax.swing.JScrollPane jScrollPaneSesiones;
    private javax.swing.JPanel jpBotonesConfe;
    private javax.swing.JPanel jpBotonesParticipantes;
    private javax.swing.JPanel jpBotonesSesiones;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPanel jpConferencias;
    private javax.swing.JPanel jpGestionFondo;
    private javax.swing.JPanel jpInfo;
    private javax.swing.JPanel jpInfoConfe;
    private javax.swing.JPanel jpInfoConfeContenido;
    private javax.swing.JPanel jpParticipantes;
    private javax.swing.JPanel jpSesiones;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionEdit;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaEdit;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraFinEdit;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHoraInicioEdit;
    private javax.swing.JLabel lblInfoConfe;
    private javax.swing.JLabel lblListado;
    private javax.swing.JLabel lblNParticipantes;
    private javax.swing.JLabel lblNParticipantesEdit;
    private javax.swing.JLabel lblNSesiones;
    private javax.swing.JLabel lblNSesionesEdit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEdit;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioEdit;
    private javax.swing.JLabel lblSesiones;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel lblTemaEdit;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
