/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxectoaad;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author a12angelpa
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpEleccionBD = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnHibernate = new javax.swing.JButton();
        btnNeodatis = new javax.swing.JButton();
        btnExist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conferencias científicas");
        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(400, 400));

        jpEleccionBD.setBackground(new java.awt.Color(204, 255, 153));
        jpEleccionBD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jpEleccionBD.setAlignmentX(50.5F);
        jpEleccionBD.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/CIENCIAS.png"))); // NOI18N
        lblTitulo.setText("CONFERENCIAS CIENTÍFICAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 0.2;
        jpEleccionBD.add(lblTitulo, gridBagConstraints);

        btnHibernate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/hibernate150x150.jpg"))); // NOI18N
        btnHibernate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHibernateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.1;
        jpEleccionBD.add(btnHibernate, gridBagConstraints);

        btnNeodatis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/neodatis150x150.jpg"))); // NOI18N
        btnNeodatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeodatisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.1;
        jpEleccionBD.add(btnNeodatis, gridBagConstraints);

        btnExist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/existdb150x150.jpg"))); // NOI18N
        btnExist.setAlignmentY(0.0F);
        btnExist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 0.1;
        jpEleccionBD.add(btnExist, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEleccionBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEleccionBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHibernateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHibernateActionPerformed
        controlador.hibernate.Hib.connect();
        jfPruebas1 lista = new jfPruebas1();
        lista.setVisible(true);
    }//GEN-LAST:event_btnHibernateActionPerformed

    private void btnNeodatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeodatisActionPerformed
        //controlador.neodatis.Neo.connect();
        jfPruebas1 lista = new jfPruebas1();
        lista.setVisible(true);
    }//GEN-LAST:event_btnNeodatisActionPerformed

    private void btnExistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistActionPerformed
        //controlador.exist.X.connect();
        jfPruebas1 lista = new jfPruebas1();
        lista.setVisible(true);
    }//GEN-LAST:event_btnExistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public JButton getBtnExist() {
        return btnExist;
    }

    public void setBtnExist(JButton btnExist) {
        this.btnExist = btnExist;
    }

    public JButton getBtnHibernate() {
        return btnHibernate;
    }

    public void setBtnHibernate(JButton btnHibernate) {
        this.btnHibernate = btnHibernate;
    }

    public JButton getBtnNeodatis() {
        return btnNeodatis;
    }

    public void setBtnNeodatis(JButton btnNeodatis) {
        this.btnNeodatis = btnNeodatis;
    }

    public JPanel getJpEleccionBD() {
        return jpEleccionBD;
    }

    public void setJpEleccionBD(JPanel jpEleccionBD) {
        this.jpEleccionBD = jpEleccionBD;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExist;
    private javax.swing.JButton btnHibernate;
    private javax.swing.JButton btnNeodatis;
    private javax.swing.JPanel jpEleccionBD;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
