/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxectoaad;

/**
 *
 * @author AnxoPregal
 */
public class Personas extends javax.swing.JFrame {

    /**
     * Creates new form Conferencias
     */
    public Personas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpCabecera = new javax.swing.JPanel();
        lblConferencia = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jpDatosConfNueva = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jsId = new javax.swing.JScrollPane();
        jEditorPane9 = new javax.swing.JEditorPane();
        jsNombre = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jcbConfirmar = new javax.swing.JCheckBox();
        lblEmail = new javax.swing.JLabel();
        jsEmail = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpCabecera.setBackground(new java.awt.Color(255, 204, 153));
        jpCabecera.setLayout(new java.awt.GridBagLayout());

        lblConferencia.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        lblConferencia.setText("Persona");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jpCabecera.add(lblConferencia, gridBagConstraints);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/guardar25.png"))); // NOI18N
        Guardar.setEnabled(false);
        Guardar.setMaximumSize(new java.awt.Dimension(25, 25));
        Guardar.setMinimumSize(new java.awt.Dimension(25, 25));
        Guardar.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jpCabecera.add(Guardar, gridBagConstraints);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/atras25.png"))); // NOI18N
        btnAtras.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAtras.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAtras.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jpCabecera.add(btnAtras, gridBagConstraints);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit25.png"))); // NOI18N
        btnEditar.setMaximumSize(new java.awt.Dimension(25, 25));
        btnEditar.setMinimumSize(new java.awt.Dimension(25, 25));
        btnEditar.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jpCabecera.add(btnEditar, gridBagConstraints);

        getContentPane().add(jpCabecera, java.awt.BorderLayout.PAGE_START);

        jpDatosConfNueva.setBackground(new java.awt.Color(204, 255, 153));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        jpDatosConfNueva.setLayout(jPanel1Layout);

        lblId.setText("DNI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jpDatosConfNueva.add(lblId, gridBagConstraints);

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblNombre, gridBagConstraints);

        jsId.setViewportView(jEditorPane9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
        jpDatosConfNueva.add(jsId, gridBagConstraints);

        jsNombre.setViewportView(jEditorPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        jpDatosConfNueva.add(jsNombre, gridBagConstraints);

        jcbConfirmar.setText("Confirmar asistencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 15);
        jpDatosConfNueva.add(jcbConfirmar, gridBagConstraints);

        lblEmail.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblEmail, gridBagConstraints);

        jsEmail.setViewportView(jEditorPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        jpDatosConfNueva.add(jsEmail, gridBagConstraints);

        getContentPane().add(jpDatosConfNueva, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEditar;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JEditorPane jEditorPane9;
    private javax.swing.JCheckBox jcbConfirmar;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPanel jpDatosConfNueva;
    private javax.swing.JScrollPane jsEmail;
    private javax.swing.JScrollPane jsId;
    private javax.swing.JScrollPane jsNombre;
    private javax.swing.JLabel lblConferencia;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
