/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxectoaad;

/**
 *
 * @author AnxoPregal
 */
public class SesionesNuevo extends javax.swing.JFrame {

    /**
     * Creates new form Conferencias
     */
    public SesionesNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpCabecera = new javax.swing.JPanel();
        lblConferencia = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jpDatosConfNueva = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTema = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        lblNSesiones = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblOradores = new javax.swing.JLabel();
        jsId = new javax.swing.JScrollPane();
        jEditorPane9 = new javax.swing.JEditorPane();
        jsNombre = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jsTema = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        jsArticulo = new javax.swing.JScrollPane();
        jEditorPane6 = new javax.swing.JEditorPane();
        jsFechaInicio = new javax.swing.JScrollPane();
        jEditorPane4 = new javax.swing.JEditorPane();
        jsHoraInicio = new javax.swing.JScrollPane();
        jEditorPane5 = new javax.swing.JEditorPane();
        jsDuracion = new javax.swing.JScrollPane();
        jEditorPane8 = new javax.swing.JEditorPane();
        jsDescripcion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jslOradores = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnAnadirSesion1 = new javax.swing.JButton();
        jpBotonesSesiones = new javax.swing.JPanel();
        btnAnadirSesion = new javax.swing.JButton();
        btnBorrarSesion = new javax.swing.JButton();
        btnInfoSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpCabecera.setBackground(new java.awt.Color(255, 204, 153));
        jpCabecera.setLayout(new java.awt.GridBagLayout());

        lblConferencia.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        lblConferencia.setText("Sesión nueva");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jpCabecera.add(lblConferencia, gridBagConstraints);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/guardar25.png"))); // NOI18N
        Guardar.setEnabled(false);
        Guardar.setMaximumSize(new java.awt.Dimension(25, 25));
        Guardar.setMinimumSize(new java.awt.Dimension(25, 25));
        Guardar.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jpCabecera.add(Guardar, gridBagConstraints);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/atras25.png"))); // NOI18N
        btnAtras.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAtras.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAtras.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jpCabecera.add(btnAtras, gridBagConstraints);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit25.png"))); // NOI18N
        btnEditar.setMaximumSize(new java.awt.Dimension(25, 25));
        btnEditar.setMinimumSize(new java.awt.Dimension(25, 25));
        btnEditar.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jpCabecera.add(btnEditar, gridBagConstraints);

        getContentPane().add(jpCabecera, java.awt.BorderLayout.PAGE_START);

        jpDatosConfNueva.setBackground(new java.awt.Color(204, 255, 153));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jpDatosConfNueva.setLayout(jPanel1Layout);

        lblId.setText("Id:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jpDatosConfNueva.add(lblId, gridBagConstraints);

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jpDatosConfNueva.add(lblNombre, gridBagConstraints);

        lblTema.setText("Tema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblTema, gridBagConstraints);

        lblFechaInicio.setText("Fecha inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblFechaInicio, gridBagConstraints);

        lblHoraInicio.setText("Hora inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblHoraInicio, gridBagConstraints);

        lblNSesiones.setText("Artículo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblNSesiones, gridBagConstraints);

        lblHoraFin.setText("Duración:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblHoraFin, gridBagConstraints);

        lblDescripcion.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 10, 0);
        jpDatosConfNueva.add(lblDescripcion, gridBagConstraints);

        lblOradores.setText("Oradores:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jpDatosConfNueva.add(lblOradores, gridBagConstraints);

        jsId.setViewportView(jEditorPane9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
        jpDatosConfNueva.add(jsId, gridBagConstraints);

        jsNombre.setViewportView(jEditorPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 0);
        jpDatosConfNueva.add(jsNombre, gridBagConstraints);

        jsTema.setViewportView(jEditorPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        jpDatosConfNueva.add(jsTema, gridBagConstraints);

        jsArticulo.setViewportView(jEditorPane6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jpDatosConfNueva.add(jsArticulo, gridBagConstraints);

        jsFechaInicio.setViewportView(jEditorPane4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        jpDatosConfNueva.add(jsFechaInicio, gridBagConstraints);

        jsHoraInicio.setViewportView(jEditorPane5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jpDatosConfNueva.add(jsHoraInicio, gridBagConstraints);

        jsDuracion.setViewportView(jEditorPane8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        jpDatosConfNueva.add(jsDuracion, gridBagConstraints);

        jsDescripcion.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(150, 100));
        jsDescripcion.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 15);
        jpDatosConfNueva.add(jsDescripcion, gridBagConstraints);

        jslOradores.setPreferredSize(new java.awt.Dimension(150, 130));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jslOradores.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 0);
        jpDatosConfNueva.add(jslOradores, gridBagConstraints);

        btnAnadirSesion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/edit25.png"))); // NOI18N
        btnAnadirSesion1.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion1.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion1.setOpaque(false);
        btnAnadirSesion1.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirSesion1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jpDatosConfNueva.add(btnAnadirSesion1, gridBagConstraints);

        jpBotonesSesiones.setBackground(new java.awt.Color(255, 0, 153));
        jpBotonesSesiones.setOpaque(false);
        jpBotonesSesiones.setLayout(new java.awt.GridBagLayout());

        btnAnadirSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/mas25.png"))); // NOI18N
        btnAnadirSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.setOpaque(false);
        btnAnadirSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAnadirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesSesiones.add(btnAnadirSesion, gridBagConstraints);

        btnBorrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/x25.png"))); // NOI18N
        btnBorrarSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.setOpaque(false);
        btnBorrarSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBorrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jpBotonesSesiones.add(btnBorrarSesion, gridBagConstraints);

        btnInfoSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proxectoaad/images/i25.png"))); // NOI18N
        btnInfoSesion.setMaximumSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.setMinimumSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.setOpaque(false);
        btnInfoSesion.setPreferredSize(new java.awt.Dimension(25, 25));
        btnInfoSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jpBotonesSesiones.add(btnInfoSesion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jpDatosConfNueva.add(jpBotonesSesiones, gridBagConstraints);

        getContentPane().add(jpDatosConfNueva, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoSesionActionPerformed

    private void btnBorrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarSesionActionPerformed

    private void btnAnadirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirSesionActionPerformed

    private void btnAnadirSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirSesion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionesNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton btnAnadirSesion;
    private javax.swing.JButton btnAnadirSesion1;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrarSesion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInfoSesion;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JEditorPane jEditorPane4;
    private javax.swing.JEditorPane jEditorPane5;
    private javax.swing.JEditorPane jEditorPane6;
    private javax.swing.JEditorPane jEditorPane8;
    private javax.swing.JEditorPane jEditorPane9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jpBotonesSesiones;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPanel jpDatosConfNueva;
    private javax.swing.JScrollPane jsArticulo;
    private javax.swing.JScrollPane jsDescripcion;
    private javax.swing.JScrollPane jsDuracion;
    private javax.swing.JScrollPane jsFechaInicio;
    private javax.swing.JScrollPane jsHoraInicio;
    private javax.swing.JScrollPane jsId;
    private javax.swing.JScrollPane jsNombre;
    private javax.swing.JScrollPane jsTema;
    private javax.swing.JScrollPane jslOradores;
    private javax.swing.JLabel lblConferencia;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNSesiones;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOradores;
    private javax.swing.JLabel lblTema;
    // End of variables declaration//GEN-END:variables
}
